# Generated by Django 5.2.6 on 2025-09-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_vote_unique_user_vote_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='polls_vote_user_id_4f723f_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'user'], name='polls_vote_poll_id_cfe401_idx'),
        ),
    ]
